[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "expat", "libxcb", "libxshmfence"]

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
